spring:
  application:
    name: springcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/DaveWPW/springcloud-config-github
          search-paths: respo
          username: DaveWPW
          password: wupeiwen93

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/