spring:
  application:
    name: springcloud-zuul

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springcloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: springcloud-web-admin-feign