spring:
  application:
    name: springcloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 7002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/