spring:
  application:
    # 应用程序名称
    name: springcloud-eureka
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    # registerWithEureka: false, fetchRegistry: false 表示服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/